# Generated by Django 5.2.6 on 2025-11-23 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=200)),
                ('farm_size', models.FloatField(help_text='size in acres')),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
