# Generated by Django 5.2.6 on 2025-10-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock'), ('dairy', 'Dairy Product'), ('poultry', 'Poultry Product'), ('other', 'Other')], max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('available_quantity', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.farmer')),
            ],
        ),
    ]
