# Generated by Django 5.2.6 on 2025-10-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_cart_alter_review_farmer_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'market')},
        ),
    ]
