# Generated by Django 5.2.6 on 2025-11-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market_images/'),
        ),
    ]
