# Generated by Django 5.2.6 on 2025-11-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_marketproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproduct',
            name='available_quantity',
            field=models.CharField(blank=True, default='In stock', max_length=100, null=True),
        ),
    ]
