# Generated by Django 5.2.6 on 2025-11-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_marketproduct_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproduct',
            name='available_quantity',
            field=models.FloatField(default=0),
        ),
    ]
