# Generated by Django 5.2.6 on 2025-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_marketproduct_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproduct',
            name='available_quantity',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
