# Generated by Django 5.2.6 on 2025-11-06 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_marketproduct_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproduct',
            name='available_quantity',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
