# Generated by Django 5.2.6 on 2025-11-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('equipment', 'Equipment'), ('feed', 'Animal Feed'), ('other', 'Other')], max_length=50)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.Farmer')),
            ],
        ),
    ]
