# Generated by Django 5.2.6 on 2025-11-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('chicken', 'Chicken'), ('sheep', 'Sheep'), ('other', 'Other')], max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('number_of_animals', models.IntegerField(blank=True, null=True)),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
                ('production', models.CharField(blank=True, help_text='e.g. litres of milk/cow or eggs per day', max_length=100, null=True)),
                ('total_production', models.IntegerField(blank=True, help_text='Total production of litres of milk/day or eggs per day', null=True)),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.Farmer')),
            ],
        ),
    ]
