# Generated by Django 5.2.6 on 2025-10-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('chicken', 'Chicken'), ('sheep', 'Sheep'), ('other', 'Other')], max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
                ('production', models.FloatField(blank=True, help_text='e.g. litres of milk/day', null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.farmer')),
            ],
        ),
    ]
