# Generated by Django 5.2.6 on 2025-11-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='production',
            field=models.CharField(blank=True, help_text='e.g. litres of milk/day or eggs per day', max_length=100, null=True),
        ),
    ]
