# Generated by Django 5.2.6 on 2025-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_alter_livestock_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='livestock',
            name='number_of_animals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='total_production',
            field=models.IntegerField(blank=True, help_text='Total production of litres of milk/day or eggs per day', null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='production',
            field=models.CharField(blank=True, help_text='e.g. litres of milk/cow or eggs per day', max_length=100, null=True),
        ),
    ]
